Phase2
IntelliSOFT-Consulting/kcc pull request #1
Opened 2021-03-15 09:14 UTC by LilianMathu

I have added "Add asset" module.

2021-03-15 13:05 UTC, moshonk requested changes
For the sake of consistency, please try to follow the existing conventions e.g. PersonEditor.php handles both adding and editing of people. Same way, AssetEditor should handle both adding and editing of assets. As such, move the logic for adding assets to the AssetEditor.php file and remove this one

2021-03-15 13:32 UTC, moshonk requested changes
As a general comment, please ensure that the changes are consistent with the existing conventions. Also, omit all test files before you make a PR. Review the changes made before submission to ensure that no unnecessary file changes have  been made

2021-03-15 13:32 UTC, moshonk commented on AssetEditor.php
> +}
Remove this piece of code. All db connection information should be fetched from the config files. Checkout the PersonEditor.php as a good example to follow.

2021-03-15 13:32 UTC, moshonk commented on AssetEditor.php
> +
Include the logic for adding Assets here on this file and remove the AddAsset.php file. Use PersonEditor.php as an example to follow

2021-03-15 13:32 UTC, moshonk commented on AssignAssets.php
> +
The work for assigning assets should be included as part of a different pull request. Please finish the add/edit/list Assets functionality first

2021-03-15 13:32 UTC, moshonk commented on CSVExport.php
> +$sSQL = 'SELECT person_custom_master.* FROM person__master ORDER BY custom_Order';
Was this change here necessary?

2021-03-15 13:32 UTC, moshonk commented on ChurchCRM/Config/Menu/Menu.php
> +        $AssetsMenu->addSubMenu(new MenuItem(gettext("Test Assets2"), "Test2Assets.php"));
Please remove these test menu items

2021-03-15 13:32 UTC, moshonk commented on Include/Functions.php
> +
Please undo this unnecessary change

2021-03-15 13:32 UTC, moshonk commented on Menu.php
> +
Please undo this unnecessary change

2021-03-15 13:32 UTC, moshonk commented on PeopleDashboard.php
> +
Please undo this unnecessary change

2021-03-15 13:32 UTC, moshonk commented on PersonEditor.php
> +        } elseif (isset($_POST[''])) {
Was this change necessary?

2021-03-15 13:32 UTC, moshonk commented on PersonView.php
> +
Please undo this unnecessary change

2021-03-15 13:32 UTC, moshonk commented on Register.php
> + *  filename    : .php
Please undo this unnecessary change

2021-03-15 13:32 UTC, moshonk commented on Staff/RegisterStaff.php
> +?>
Please undo this unnecessary file

2021-03-15 13:32 UTC, moshonk commented on Staff/ViewStaff.php
> +        <a href="RegisterStaff.php" class="btn btn-success" >Add new</a>
Please remove this unnecessary file

2021-03-15 13:32 UTC, moshonk commented on Test2Assets.php
> +<?php
Please remove this test file

2021-03-15 13:32 UTC, moshonk commented on TestAssets.php
> +<?php
Please remove this test file

2021-03-15 13:32 UTC, moshonk commented on locale/js/af_ZA.js
> +    "Assets": "Assets Editor",
I don't think this change was necessary. It's inconsistent with the rest of the content. Please undo it.

2021-03-15 13:32 UTC, moshonk commented on locale/js/ar_EG.js
> +    "Assets Editor": "",
I don't think this change was necesasry. Please undo it.

2021-03-15 13:32 UTC, moshonk commented on mysql/install/Install.sql
> +-- Table structure for `staff`
Please undo these changes

2021-03-15 13:32 UTC, moshonk commented on members/self-register.php
> +
Please undo this change

2021-03-15 13:32 UTC, moshonk commented on integrityCheck.json
> -{"status":"failure","message":"One or more files failed signature validation","files":[{"filename":"ChurchCRM\/Config\/Menu\/Menu.php","status":"Hash Mismatch","expectedhash":"618053483cfb1510b44033c
This looks like another unnecessary change. Please undo it.

2021-03-16 06:50 UTC, LilianMathu commented on integrityCheck.json
> -{"status":"failure","message":"One or more files failed signature validation","files":[{"filename":"ChurchCRM\/Config\/Menu\/Menu.php","status":"Hash Mismatch","expectedhash":"618053483cfb1510b44033c
I did not add this one. I wouldn.t know what it is the right.

2021-03-16 06:50 UTC, LilianMathu commented on integrityCheck.json
> -{"status":"failure","message":"One or more files failed signature validation","files":[{"filename":"ChurchCRM\/Config\/Menu\/Menu.php","status":"Hash Mismatch","expectedhash":"618053483cfb1510b44033c
It seems auto generated

2021-04-14 06:16 UTC, LilianMathu commented
@moshonk Please review my work for asset management. Kind regards!

2021-04-16 05:52 UTC, moshonk commented
@LilianMathu, you have conflicts in key files that need to be resolved

2021-04-16 06:54 UTC, moshonk requested changes
@LilianMathu, Please see my review comments and reach out in case you need further clarification

2021-04-16 06:54 UTC, moshonk commented on AssetEditor.php
> +}
This condition has no code block. Please remove it, if it serves no purpose, otherwise add the intended logic

2021-04-16 06:54 UTC, moshonk commented on AssetList.php
> +  $sSQL = "DELETE from assets WHERE assetID='$assetID'";
This is a hard delete operation that may lead to loss of important information if executed. Need to change this to a soft delete operation. Follow these steps:

- Add a column to the `assets` table e.g. asst_Deleted of datatype ENUM('FALSE','TRUE') where a `TRUE` value representts a deleted record
- Update this sql to an update statement `UPDATE assets SET aat_Deleted = 'TRUE'WHERE assetID='$assetID'`

2021-04-16 06:54 UTC, moshonk commented on AssetList.php
> +// }
Remove this commented code block.

2021-04-16 06:54 UTC, moshonk commented on AssignAssets.php
> +    $sSQL = "UPDATE assignassets SET assetName = '".$sassetName."', assignedTo = '".$sassignedTo."',  assignedBy = '".$sassignedBy."', serialNumber = '".$sserialNumber."',  assetCondition = '".$sasse
This statement will update all records because it has no `WHERE` clause. Please correct it

2021-04-16 06:54 UTC, moshonk commented on AssignAssets.php
> +// echo RunQuery($sSQL);
Please remove this commented code

2021-04-16 06:54 UTC, moshonk commented on v2/templates/people/person-list.php
> +                    <?php if (!isset($_SESSION['aPeople Cart']) || !in_array($per_ID, $_SESSION['aPeopleCart'], false)) {
Was this update neccessary, please check?

2021-04-19 05:09 UTC, LilianMathu commented on AssetEditor.php
> +if($iassetID < 1){
I added this line before the code block

$assetID =  InputUtils::LegacyFilterInput($_GET['assetID'], 'int');

2021-04-19 07:24 UTC, LilianMathu commented on AssetEditor.php
> +    $sSQL = "UPDATE assets SET assetName = '".$sassetName."', serialNumber = '".$sserialNumber."', quantity = '".$squantity."',  assetCondition = '".$iassetCondition."', assetDescription = '".$sasset
I added this snippet..
           WHERE assetID = '$assetID'";

2021-04-19 07:25 UTC, LilianMathu commented on AssetEditor.php
> +}
I removed this code

2021-04-19 07:48 UTC, LilianMathu commented on AssetList.php
> +  $sSQL = "DELETE from assets WHERE assetID='$assetID'";
// delete an asset
if(isset($_GET['delete'])){
  $assetID = $_GET['delete'];
  $sSQL = "UPDATE assets SET assetDeleted = 'TRUE' WHERE assetID='$assetID'";
}

replaced the code block with this one

2021-04-19 07:49 UTC, LilianMathu commented on AssetList.php
> +// }
Removed

2021-04-19 07:55 UTC, LilianMathu commented on AssignAssets.php
> +    $sSQL = "UPDATE assignassets SET assetName = '".$sassetName."', assignedTo = '".$sassignedTo."',  assignedBy = '".$sassignedBy."', serialNumber = '".$sserialNumber."',  assetCondition = '".$sasse
Replaced with this code

    //New asset assign
    if($assignID < 1){
        $sSQL = "INSERT INTO assignassets(assetName, assignedTo, assignedBy, serialNumber, assetCondition, assetCategory, assignDate, returnDate)
                VALUES('".$sassetName."', '".$sassignedTo."', '".$sassignedBy."', '".$sserialNumber."', '".$sassetCondition."', '".$sassetCategory."', '".$sassignDate."', '".$sreturnDate."')";
    } else {
        $sSQL = "UPDATE assignassets SET assetName = '".$sassetName."', assignedTo = '".$sassignedTo."',  assignedBy = '".$sassignedBy."', serialNumber = '".$sserialNumber."',  assetCondition = '".$sassetCondition."', assetCategory = '".$sassetCategory."',  assignDate = '".$sassignDate."', returnDate = '".$sreturnDate."'
        WHERE assignID = '$assignID' 
         ";
    }

2021-04-19 08:11 UTC, LilianMathu commented on AssignAssets.php
> +// echo RunQuery($sSQL);
@moshonk
Done

2021-04-19 08:13 UTC, LilianMathu commented on v2/templates/people/person-list.php
> +                    <?php if (!isset($_SESSION['aPeople Cart']) || !in_array($per_ID, $_SESSION['aPeopleCart'], false)) {
@moshonk
I have undone the change

2021-04-19 08:14 UTC, LilianMathu commented
@moshonk I have submitted the code for sunday services. I am still working on a few things on it. Please review.

2021-04-20 12:40 UTC, moshonk requested changes

2021-04-21 08:53 UTC, LilianMathu commented
@moshonk I have committed the file, with commit message "conflicting file". Please review and offer feedback.

2021-04-21 12:14 UTC, LilianMathu commented on Include/Header-HTML-Scripts.php
> +<title>KCC: <?= $sPageTitle ?></title>
Resolved

2021-04-21 12:15 UTC, LilianMathu commented on AssignAssets.php
> +    $sreturnDate = InputUtils::LegacyFilterInput($_POST['returnDate']);
If no date is input, the system picks the date as 1970

2021-04-21 12:17 UTC, LilianMathu commented on Staff/ViewStaff.php
> +        <a href="RegisterStaff.php" class="btn btn-success" >Add new</a>
@moshonk 
I don't have this file on my code.

2021-04-21 12:18 UTC, LilianMathu commented on Test2Assets.php
> +<?php
Resolved

2021-04-22 04:27 UTC, moshonk commented on AssetList.php
> +  $sSQL = "DELETE from assets WHERE assetID='$assetID'";
You seem to have undone the previous changes @LilianMathu

2021-11-15 06:27 UTC, closed without merging