Phaseone
IntelliSOFT-Consulting/kcc pull request #4
Opened 2021-06-18 10:04 UTC by LilianMathu

Please review and offer feedback.

2021-06-18 10:09 UTC, LilianMathu commented
@moshonk 
Please review and offer feedback.

2021-06-22 12:59 UTC, moshonk requested changes
@Lilian, please see my review comments.

2021-06-22 12:59 UTC, moshonk commented on ChurchCRM/Bootstrapper.php
> +          self::$bootStrapLogger->debug("Session initialized: " . $Name);
Was this change necessary? I don't see anywhere where the `$Name` variable has been initialized and/or set

2021-06-22 12:59 UTC, moshonk commented on FundRaiserEditor.php
> +            $['iCurrentFundraiser'] = $iFundRaiserID;
Any reason for this change?

2021-06-22 12:59 UTC, moshonk commented on Include/Functions.php
> +        if (SystemConfig::getValue('sLogLevel') == "200") { // debug level
You need to revert to the old log level check value (100) since the application is going into production

2021-06-22 12:59 UTC, moshonk commented on PersonEditor.php
> +    <input type="submit" class="btn btn-primary" id="PersonSaveButton" value="<?= gettext('Save') ?>" name="PersonSubmit" onsubmit="alert('New person added');">
Is this JS alert necessary here?

2021-06-22 12:59 UTC, moshonk commented on skin/external/adminlte/AdminLTE.min.css
> + */html,body{height:100%}.layout-boxed html,.layout-boxed body{height:100%}body{font-family:'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:400;overflow-x:hidden;overflow-y:
Did you make any changes to this file? Being a minified file, I doubt there was any need to directly update it.

2021-06-22 12:59 UTC, moshonk commented on integrityCheck.json
> +{"status":"failure","message":"One or more files failed signature validation","files":[{"filename":"AddDonors.php","status":"Hash Mismatch","expectedhash":"9d726d2d41fd10d85fafc8276cb9f67c08f1b160","
Please add this file to the `.gitignore` list so that next time it is auto-updated, you don't have to update the changes.

2021-06-22 12:59 UTC, moshonk commented on Include/Footer.php
> +<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
I see you changed the default date picker library. Reason?

2021-06-23 02:18 UTC, LilianMathu commented on ChurchCRM/Bootstrapper.php
> +          self::$bootStrapLogger->debug("Session initialized: " . $Name);
Not really, I've reset it to how it was.

2021-06-23 02:20 UTC, LilianMathu commented on FundRaiserEditor.php
> +            $['iCurrentFundraiser'] = $iFundRaiserID;
This one must have been edited by mistake. I was looking at how sessions have been implemented, and it could have been deleted in the process. I will be more careful.

2021-06-23 02:22 UTC, LilianMathu commented on Include/Functions.php
> +        if (SystemConfig::getValue('sLogLevel') == "200") { // debug level
I will definitely check out the different log levels and what they mean. Thanks!

2021-06-23 02:24 UTC, LilianMathu commented on PersonEditor.php
> +    <input type="submit" class="btn btn-primary" id="PersonSaveButton" value="<?= gettext('Save') ?>" name="PersonSubmit" onsubmit="alert('New person added');">
I was trying to add an alert when a new person is added to the system. Let me do it right then push the code again.

2021-06-23 02:34 UTC, LilianMathu commented on skin/external/adminlte/AdminLTE.min.css
> + */html,body{height:100%}.layout-boxed html,.layout-boxed body{height:100%}body{font-family:'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:400;overflow-x:hidden;overflow-y:
Probably this was before I enquired about editing the skin like three months ago. I will copy and paste the entire file since it will take a long time to trace the change.

2021-06-23 02:36 UTC, LilianMathu commented on integrityCheck.json
> +{"status":"failure","message":"One or more files failed signature validation","files":[{"filename":"AddDonors.php","status":"Hash Mismatch","expectedhash":"9d726d2d41fd10d85fafc8276cb9f67c08f1b160","
Done.

2021-06-23 02:37 UTC, LilianMathu commented on Include/Footer.php
> +<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
The other one was now working well. I used the same datepicker, but a more recent version.

2021-06-23 02:57 UTC, moshonk commented on skin/external/adminlte/AdminLTE.min.css
> + */html,body{height:100%}.layout-boxed html,.layout-boxed body{height:100%}body{font-family:'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:400;overflow-x:hidden;overflow-y:
Check out this link on how you can revert a single file to a point in history https://dev.to/lofiandcode/git-and-github-how-to-revert-a-single-file-dha

2021-06-23 03:01 UTC, moshonk commented on Include/Footer.php
> +<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
If that's the only reason, then please revert it so that there is consistency in the code.

2021-06-24 13:03 UTC, LilianMathu commented on Include/Footer.php
> +<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
@moshonk
I don't understand. Like revert to the one that was there initially?

2021-06-25 00:54 UTC, moshonk commented on Include/Footer.php
> +<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
Your comment above states that the older version was working well, right?

2021-06-28 02:00 UTC, moshonk requested changes

2021-06-28 02:00 UTC, moshonk commented on PersonEditor.php
> +           onclick="javascript:setTimeout(document.location='v2/people',5000);">
Is there a good reason to introduce this 5sec delay here?

2021-06-28 02:00 UTC, moshonk commented on PersonEditor.php
>      <input type="submit" class="btn btn-primary" id="PersonSaveButton" value="<?= gettext('Save') ?>" name="PersonSubmit" onsubmit="alert('New person added');">
Now that you've implemented the alert, please remove the js alert code  `onsubmit="alert('New person added');`

2021-06-28 02:00 UTC, moshonk commented on staticFiles/css/style.css
> +.block{
Please rename this css class to something like `display-block` so that it makes semantic sense

2021-06-28 02:00 UTC, moshonk commented on PersonEditor.php
> +
This would be the best place to introduce the alert via something like:

```
echo ("<script>
    const alert = document.getElementById('record_saved');
    alert.classList.add('block')

    setTimeout(()=>alert.classList.remove('block'),5000)</script>";

2021-06-28 02:00 UTC, moshonk commented on PersonEditor.php
> +
That's how you can print a js script using php. Check this link out. https://www.geeksforgeeks.org/how-to-run-javascript-from-php/

2021-06-28 07:26 UTC, LilianMathu commented on Include/Footer.php
> +<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
@moshonk
The other date picker was not working well. That's a typing error. 
It was faulty, which is why I changed it.

2021-06-28 07:29 UTC, LilianMathu commented on PersonEditor.php
>      <input type="submit" class="btn btn-primary" id="PersonSaveButton" value="<?= gettext('Save') ?>" name="PersonSubmit" onsubmit="alert('New person added');">
@moshonk
Done.

2021-06-28 08:32 UTC, LilianMathu commented on PersonEditor.php
> +           onclick="javascript:setTimeout(document.location='v2/people',5000);">
@moshonk
Yes. This delay allows the user to see the alert before the page redirects.

2021-06-28 08:36 UTC, LilianMathu commented on staticFiles/css/style.css
> +.block{
@moshonk
Done.

2021-06-28 08:37 UTC, LilianMathu commented on PersonEditor.php
> +
@moshink

Done.

2021-06-28 08:38 UTC, LilianMathu commented
@moshonk I have implemented all the changes you suggested, and left comments on a few. Please review and revert.

2021-06-28 08:42 UTC, moshonk commented on PersonEditor.php
> +           onclick="javascript:setTimeout(document.location='v2/people',5000);">
Ok. This is the cancel button. What alert are you showing when the cancel button is clicked?

2021-06-28 08:46 UTC, moshonk commented on PersonEditor.php
> +</script>
Following the change made above, this snippet is not necessary any more, right?

2021-06-28 08:47 UTC, moshonk commented on staticFiles/css/style.css
> +.block{
Ok. Can't see the change here though.

2021-06-28 08:49 UTC, moshonk commented on PersonEditor.php
> +
Ok. Can't see the change here though. It's possible that you've not pushed it yet

2021-06-28 08:54 UTC, LilianMathu commented on PersonEditor.php
> +</script>
@moshonk
I have retained this, and deleted the php code. I'm referencing the form using the id.

2021-06-28 09:16 UTC, LilianMathu commented
@moshonk I have pushed the new changes. Kindly review and revert.

2021-06-29 03:50 UTC, moshonk commented on staticFiles/css/style.css
> +.disp-block{
Please change this class name to `display-block` to make the meaning obvious

2021-06-29 04:07 UTC, moshonk requested changes
@LilianMathu, the execution of the alert logic is not correct (Ideally, the alert should be executed only when a record is successfully added, right?). I had proposed a workaround for it. Can you please check it out. Let me know if you are having challenges with any challenges or reservations.

Also, the delay that you've set on the cancel buttons is unnecessary (Refer to my previous comments too) and should be removed.

2021-06-29 04:07 UTC, moshonk commented on FamilyEditor.php
> +
This script will execute when the form is submitted, regardless of whether validation succeeds or fails. Please refer to a previous comment on a workaround.

2021-06-29 06:06 UTC, LilianMathu commented on staticFiles/css/style.css
> +.disp-block{
@moshonk
With the display-block, the style wasn't picking. Seems like there is another display-block in the code.

2021-06-29 06:08 UTC, LilianMathu commented on PersonEditor.php
>  })
@moshonk I will revisit and make the changes.

2021-06-30 19:56 UTC, LilianMathu commented
@moshonk Hi Ken. I have pushed code without the alert. Please review and revert.

2021-07-01 03:54 UTC, moshonk approved these changes

2021-07-01 03:58 UTC, moshonk approved these changes

2021-07-01 04:01 UTC, moshonk approved these changes

2021-07-01 04:29 UTC, LilianMathu commented
Phase one closed.

2021-07-01 04:43 UTC, LilianMathu commented
@moshonk Thank you. Is it possible to merge with the develop branch?

2021-07-01 05:06 UTC, merged