deployment files
IntelliSOFT-Consulting/kcc pull request #5
Opened 2021-06-29 08:43 UTC by LilianMathu

@moshonk

Please review the deployment files for release one and offer feedback.

2021-06-29 09:41 UTC, moshonk commented on docker/docker-compose.test-apache.yaml
> +      - /home/lmathu/kcc:/var/www/html
Put the project files in the `/opt/` directory

2021-06-29 09:43 UTC, LilianMathu commented on docker/docker-compose.test-apache.yaml
> +      - /home/lmathu/kcc:/var/www/html
@moshonk 
Okay.

2021-06-29 09:43 UTC, moshonk requested changes
The deployment location should  the `/opt`` directory

2021-06-30 09:42 UTC, LilianMathu commented
@moshonk Hi Ken. I have made the changes you requested. Please review and revert.

2021-07-01 04:42 UTC, LilianMathu commented
@moshonk Please review and offer feedback.

2021-07-01 11:50 UTC, closed without merging